// Mock Data Generator for TazeKuru
export const mockData = {

    tags: ["Glutensiz", "Vegan", "Organik", "Ev Yapımı", "Taze", "Geleneksel", "Sıcak", "Soğuk"],

    products: [
        {
            product_id: 1,
            name: "Ev Yapımı Mantı",
            description: "Anne elinden ince açılmış, özenle hazırlanmış geleneksel mantı. Yoğurt ve tereyağı soslu.",
            price: 85,
            quantity: 12,
            photo: "https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800",
            seller_id: 1,
            upload_date: "2025-01-27",
            is_available: 1,
            category_id: 1,
            tags: ["Ev Yapımı", "Geleneksel"],
            users: { first_name: "Ayşe", last_name: "Yılmaz", rating: 4.9 },
            views: 245,
            sales: 34,
            featured: true
        },
        {
            product_id: 2,
            name: "Sıcak Mercimek Çorbası",
            description: "Taze sebzelerle hazırlanan sağlıklı ve doyurucu mercimek çorbası. Limon ile servis edilir.",
            price: 25,
            quantity: 20,
            photo: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
            seller_id: 2,
            upload_date: "2025-01-27",
            is_available: 1,
            category_id: 5,
            tags: ["Sıcak", "Vegan", "Organik"],
            users: { first_name: "Mehmet", last_name: "Demir", rating: 4.7 },
            views: 189,
            sales: 56,
            featured: false
        },
        {
            product_id: 3,
            name: "Baklava (1 kg)",
            description: "Antep fıstıklı, kat kat açılmış yufka ile hazırlanmış geleneksel baklava.",
            price: 220,
            quantity: 8,
            photo: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800",
            seller_id: 3,
            upload_date: "2025-01-26",
            is_available: 1,
            category_id: 3,
            tags: ["Geleneksel", "Taze"],
            users: { first_name: "Fatma", last_name: "Kaya", rating: 5.0 },
            views: 312,
            sales: 28,
            featured: true
        },
        {
            product_id: 4,
            name: "Taze Sezar Salata",
            description: "Çıtır marul, parmesan peyniri, kruton ve özel sezar sosu ile hazırlanmış taze salata.",
            price: 45,
            quantity: 15,
            photo: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800",
            seller_id: 4,
            upload_date: "2025-01-27",
            is_available: 1,
            category_id: 4,
            tags: ["Taze", "Soğuk"],
            users: { first_name: "Zeynep", last_name: "Şahin", rating: 4.8 },
            views: 167,
            sales: 42,
            featured: false
        },
        {
            product_id: 5,
            name: "Ev Böreği (Tepsi)",
            description: "Su böreği tadında, el açması yufka ile hazırlanmış peynirli tepsi böreği.",
            price: 120,
            quantity: 6,
            photo: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
            seller_id: 1,
            upload_date: "2025-01-26",
            is_available: 1,
            category_id: 2,
            tags: ["Ev Yapımı", "Sıcak"],
            users: { first_name: "Ayşe", last_name: "Yılmaz", rating: 4.9 },
            views: 298,
            sales: 38,
            featured: true
        },
        {
            product_id: 6,
            name: "Menemen (2 Porsiyon)",
            description: "Taze domatesler, biber ve yumurta ile geleneksel menemen. Sıcak servis edilir.",
            price: 35,
            quantity: 18,
            photo: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800",
            seller_id: 2,
            upload_date: "2025-01-27",
            is_available: 1,
            category_id: 6,
            tags: ["Sıcak", "Kahvaltılık"],
            users: { first_name: "Mehmet", last_name: "Demir", rating: 4.7 },
            views: 156,
            sales: 51,
            featured: false
        },
        {
            product_id: 7,
            name: "Vegan Buddha Bowl",
            description: "Kinoa, nohut, avokado, taze sebzeler ve tahini sosu ile hazırlanmış sağlıklı bowl.",
            price: 55,
            quantity: 10,
            photo: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
            seller_id: 4,
            upload_date: "2025-01-27",
            is_available: 1,
            category_id: 4,
            tags: ["Vegan", "Organik", "Taze"],
            users: { first_name: "Zeynep", last_name: "Şahin", rating: 4.8 },
            views: 203,
            sales: 29,
            featured: false
        },
        {
            product_id: 8,
            name: "Künefe (Porsiyon)",
            description: "Hatay usulü, taze kadayıf ile hazırlanmış özel künefe. Sıcak servis edilir.",
            price: 65,
            quantity: 14,
            photo: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800",
            seller_id: 3,
            upload_date: "2025-01-26",
            is_available: 1,
            category_id: 3,
            tags: ["Geleneksel", "Sıcak"],
            users: { first_name: "Fatma", last_name: "Kaya", rating: 5.0 },
            views: 287,
            sales: 47,
            featured: true
        },
    ],

    sellers: [
        { user_id: 1, username: "ayse_mutfak", first_name: "Ayşe", last_name: "Yılmaz", rating: 4.9, total_sales: 234, badge: "⭐ Yıldız Satıcı" },
        { user_id: 2, username: "mehmet_chef", first_name: "Mehmet", last_name: "Demir", rating: 4.7, total_sales: 189, badge: "🔥 Popüler" },
        { user_id: 3, username: "fatma_tatli", first_name: "Fatma", last_name: "Kaya", rating: 5.0, total_sales: 312, badge: "👑 Premium" },
        { user_id: 4, username: "zeynep_organik", first_name: "Zeynep", last_name: "Şahin", rating: 4.8, total_sales: 156, badge: "🌱 Organik" },
    ],

    stats: {
        totalProducts: 248,
        totalSellers: 67,
        totalOrders: 1823,
        avgRating: 4.8,
    }
};
